"""
Django settings for Lyneerp project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

from django.contrib import staticfiles

# from Lyneerp.settings import env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!


from dotenv import load_dotenv

load_dotenv()

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev")
DEBUG = os.getenv("DJANGO_DEBUG", "0") == "1"
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "lyneerp.com,rh.lyneerp.com").split(",")
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mozilla_django_oidc',
    'rest_framework',
    'drf_spectacular',
    'storages',  # pour MinIO (S3)
    'hr',
    'tenants',
    'redis',
]

MIDDLEWARE = [

    "tenants.middleware.TenantMiddleware",
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    "tenants.middleware.TenantResolutionMiddleware",
    'django.middleware.csrf.CsrfViewMiddleware',
    "tenants.middleware.TenantSessionMiddleware",
    "tenants.middleware.RequestTenantMiddleware",
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'Lyneerp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Lyneerp.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
AUTHENTICATION_BACKENDS = [
    "mozilla_django_oidc.auth.OIDCAuthenticationBackend",
    "django.contrib.auth.backends.ModelBackend",
]

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "hr.auth.KeycloakJWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}
SPECTACULAR_SETTINGS = {"TITLE": "LYNE-ERP RH API", "VERSION": "1.0.0"}

# DB
if os.getenv("DB_ENGINE") == "postgres":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PASSWORD"),
            "HOST": os.getenv("DB_HOST"),
            "PORT": os.getenv("DB_PORT"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / os.getenv("DB_NAME", "db.sqlite3"),
        }
    }

# MinIO via django-storages
AWS_S3_ENDPOINT_URL = os.getenv("S3_ENDPOINT")
AWS_ACCESS_KEY_ID = os.getenv("S3_ACCESS_KEY")
AWS_SECRET_ACCESS_KEY = os.getenv("S3_SECRET_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("S3_BUCKET", "lyneerp")
AWS_S3_REGION_NAME = "us-east-1"
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_S3_ADDRESSING_STYLE = "path"
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Static / Media
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")  # dossier cible de collectstatic

# (facultatif) si tu as un dossier /static dans le code source pour tes assets non collectés
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

LOGIN_URL = "/oidc/authenticate/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# LOGIN_URL = '/login/'
# LOGIN_REDIRECT_URL = '/'  # Redirection après connexion réussie
# LOGOUT_REDIRECT_URL = '/login/'

# Optionnel : nom du cookie “tenant”
TENANT_SESSION_KEY = "current_tenant"
REMEMBER_ME_SESSION_AGE = 60 * 60 * 24 * 30  # 30 jours
SESSION_COOKIE_AGE = 60 * 60 * 2  # 2h (si pas remember me)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # expir. à la fermeture (par défaut)


KEYCLOAK_BASE_URL = os.getenv("KEYCLOAK_BASE_URL", "https://sso.lyneerp.com")
KEYCLOAK_CLIENT_ID = os.getenv("KEYCLOAK_CLIENT_ID", "rh-core")
KEYCLOAK_CLIENT_SECRET = os.getenv("KEYCLOAK_CLIENT_SECRET", "")  # vide si client public
KEYCLOAK_USE_REALM_PER_TENANT = True  # ou False si un seul realm global

# Mapping tenant -> realm (exemple)
TENANT_REALMS = {
    "acme": "lyneerp",
    "demo": "lyneerp",
}
OIDC_SESSION_KEY = "oidc_user"
# Optionnel
TENANT_SUBDOMAIN_REGEX = r"^(?P<tenant>[a-z0-9-]+)\.(?:rh\.)?lyneerp\.com$"
DEFAULT_TENANT = None  # ou "default"
# Où stocker les infos utilisateur dans la session

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Sufficient pour un retour GET top-level depuis IdP
SESSION_COOKIE_SAMESITE = "Lax"

# Recommandé si tu utilises des sous-domaines
SESSION_COOKIE_DOMAIN = ".lyneerp.com"

CSRF_TRUSTED_ORIGINS = ["https://rh.lyneerp.com", "https://*.lyneerp.com"]


# --- Garde l'issuer et l'AUTH endpoint publics (utilisés par le navigateur) ---
OIDC_OP_ISSUER = "https://sso.lyneerp.com/realms/lyneerp"
OIDC_OP_AUTHORIZATION_ENDPOINT = f"{OIDC_OP_ISSUER}/protocol/openid-connect/auth"

# --- Endpoints appelés côté serveur : utilise le DNS docker du service keycloak ---
OIDC_OP_TOKEN_ENDPOINT= "http://keycloak:8080/realms/lyneerp/protocol/openid-connect/token"
OIDC_OP_JWKS_ENDPOINT = "http://keycloak:8080/realms/lyneerp/protocol/openid-connect/certs"
OIDC_OP_USER_ENDPOINT = "http://keycloak:8080/realms/lyneerp/protocol/openid-connect/userinfo"

OIDC_RP_CLIENT_ID = "rh-core"                    # client type "Public" dans Keycloak
OIDC_RP_CLIENT_SECRET = None                     # None pour client public
OIDC_OP_ISSUER = "https://sso.lyneerp.com/realms/lyneerp"
# OIDC_OP_AUTHORIZATION_ENDPOINT = f"{OIDC_OP_ISSUER}/protocol/openid-connect/auth"
# OIDC_OP_TOKEN_ENDPOINT = f"{OIDC_OP_ISSUER}/protocol/openid-connect/token"
# OIDC_OP_USER_ENDPOINT = f"{OIDC_OP_ISSUER}/protocol/openid-connect/userinfo"
# OIDC_OP_JWKS_ENDPOINT = f"{OIDC_OP_ISSUER}/protocol/openid-connect/certs"

# OIDC_OP_TOKEN_ENDPOINT = "http://keycloak:8080/realms/lyneerp/protocol/openid-connect/token"
# Algorithme de signature attendu pour les ID tokens (Keycloak = RS256 par défaut)
OIDC_RP_SIGN_ALGO = "RS256"
# 1) Scopes demandés (sinon certains IdP ne renvoient pas email/username)
OIDC_RP_SCOPES = "openid email profile"

# 2) Timeout des appels OIDC (échange code->token)
OIDC_TIMEOUT = 10

# 3) (Optionnel) Stocker les tokens en session si tu en as besoin après login
OIDC_STORE_ID_TOKEN = True
OIDC_STORE_ACCESS_TOKEN = True


SESSION_ENGINE = "django.contrib.sessions.backends.cache"
CACHES = {
  "default": {
    "BACKEND": "django.core.cache.backends.redis.RedisCache",
    "LOCATION": "redis://redis:6379/1",
  }
}