# Generated by Django 4.2.25 on 2025-11-07 10:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.SlugField()),
                ('plan', models.CharField(max_length=32)),
                ('seats', models.PositiveIntegerField(default=5)),
                ('valid_until', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Licence',
                'verbose_name_plural': 'Licences',
                'db_table': 'licenses',
            },
        ),
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.SlugField()),
                ('user_sub', models.CharField(max_length=128)),
                ('user_email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Attribution de siège',
                'verbose_name_plural': 'Attributions de sièges',
                'db_table': 'seat_assignments',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('plan_type', models.CharField(choices=[('STARTER', 'Starter'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise')], default='STARTER', max_length=20)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenants',
            },
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Propriétaire'), ('ADMIN', 'Administrateur'), ('MANAGER', 'Manager'), ('MEMBER', 'Membre'), ('VIEWER', 'Observateur')], default='MEMBER', max_length=20)),
                ('enabled_services', models.JSONField(blank=True, default=list, help_text='Liste des services activés pour cet utilisateur')),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_access', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_users', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre du Tenant',
                'verbose_name_plural': 'Membres des Tenants',
                'db_table': 'tenant_users',
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('RH', 'Ressources Humaines'), ('PROJET', 'Gestion de Projet'), ('COMMERCIAL', 'Commercial'), ('LOGISTIQUE', 'Logistique'), ('COMPTABILITE', 'Comptabilité'), ('INVENTAIRE', 'Gestion des stocks')], max_length=20)),
                ('license_type', models.CharField(choices=[('BASIC', 'Basic'), ('PRO', 'Professional'), ('ENTERPRISE', 'Enterprise')], max_length=20)),
                ('period', models.CharField(choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel')], default='monthly', max_length=10)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('external_subscription_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(default='fr', max_length=10)),
                ('timezone', models.CharField(default='Africa/Abidjan', max_length=50)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('require_2fa', models.BooleanField(default=False)),
                ('session_timeout', models.PositiveIntegerField(default=60)),
                ('max_login_attempts', models.PositiveIntegerField(default=5)),
                ('email_notifications', models.BooleanField(default=True)),
                ('billing_notifications', models.BooleanField(default=True)),
                ('security_notifications', models.BooleanField(default=True)),
                ('service_configs', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Configuration Tenant',
                'verbose_name_plural': 'Configurations Tenants',
                'db_table': 'tenant_settings',
            },
        ),
        migrations.CreateModel(
            name='TenantService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('RH', 'Ressources Humaines'), ('PROJET', 'Gestion de Projet'), ('COMMERCIAL', 'Commercial'), ('LOGISTIQUE', 'Logistique'), ('COMPTABILITE', 'Comptabilité'), ('INVENTAIRE', 'Gestion des stocks')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('license_type', models.CharField(choices=[('BASIC', 'Basic'), ('PRO', 'Professional'), ('ENTERPRISE', 'Enterprise')], default='BASIC', max_length=20)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('EXPIRED', 'Expiré'), ('SUSPENDED', 'Suspendu'), ('CANCELLED', 'Annulé')], default='ACTIVE', max_length=12)),
                ('external_license_id', models.CharField(blank=True, help_text='ID licence/abonnement côté fournisseur (Stripe/OM/Key)', max_length=120)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_services', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Service du Tenant',
                'verbose_name_plural': 'Services des Tenants',
                'db_table': 'tenant_services',
            },
        ),
        migrations.CreateModel(
            name='TenantInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(choices=[('OWNER', 'Propriétaire'), ('ADMIN', 'Administrateur'), ('MANAGER', 'Manager'), ('MEMBER', 'Membre'), ('VIEWER', 'Observateur')], default='MEMBER', max_length=20)),
                ('enabled_services', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptée'), ('EXPIRED', 'Expirée'), ('REVOKED', 'Révoquée')], default='PENDING', max_length=20)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_invitations',
            },
        ),
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_domains',
            },
        ),
        migrations.CreateModel(
            name='TenantBilling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_breakdown', models.JSONField(default=dict, help_text='Détail du coût par service')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ISSUED', 'Émise'), ('PAID', 'Payée'), ('OVERDUE', 'En retard'), ('CANCELLED', 'Annulée')], default='DRAFT', max_length=20)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('pdf_url', models.CharField(blank=True, max_length=255)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Facturation Tenant',
                'verbose_name_plural': 'Facturations Tenants',
                'db_table': 'tenant_billing',
            },
        ),
        migrations.CreateModel(
            name='TenantActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('USER_LOGGED_IN', 'Connexion utilisateur'), ('USER_INVITED', 'Utilisateur invité'), ('USER_ROLE_CHANGED', 'Rôle utilisateur modifié'), ('SERVICE_ACTIVATED', 'Service activé'), ('SERVICE_CONFIGURED', 'Service configuré'), ('SETTINGS_UPDATED', 'Paramètres modifiés'), ('BILLING_UPDATED', 'Facturation modifiée')], max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'activité Tenant",
                'verbose_name_plural': "Logs d'activité Tenants",
                'db_table': 'tenant_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['slug'], name='tenants_slug_3181c2_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['domain'], name='tenants_domain_726e44_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['is_active'], name='tenants_is_acti_ec1713_idx'),
        ),
        migrations.AddField(
            model_name='seatassignment',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='tenants.license'),
        ),
        migrations.AddField(
            model_name='seatassignment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='license',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['tenant', 'user'], name='tenant_user_tenant__16e2fa_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['role'], name='tenant_user_role_00f530_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['is_active'], name='tenant_user_is_acti_a9afac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantuser',
            unique_together={('tenant', 'user')},
        ),
        migrations.AddIndex(
            model_name='tenantsubscription',
            index=models.Index(fields=['tenant', 'service', 'started_at'], name='tenant_subs_tenant__f2e395_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantservice',
            index=models.Index(fields=['tenant', 'service'], name='tenant_serv_tenant__0d80bb_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantservice',
            index=models.Index(fields=['is_active'], name='tenant_serv_is_acti_da5408_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantservice',
            index=models.Index(fields=['license_type'], name='tenant_serv_license_9318ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantservice',
            unique_together={('tenant', 'service')},
        ),
        migrations.AddIndex(
            model_name='tenantinvitation',
            index=models.Index(fields=['tenant', 'email'], name='tenant_invi_tenant__edd09b_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantinvitation',
            index=models.Index(fields=['token'], name='tenant_invi_token_8b1449_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantinvitation',
            index=models.Index(fields=['status'], name='tenant_invi_status_6525df_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantinvitation',
            index=models.Index(fields=['expires_at'], name='tenant_invi_expires_74dd72_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantinvitation',
            constraint=models.CheckConstraint(check=models.Q(('expires_at__gt', models.F('created_at'))), name='invite_expires_after_creation'),
        ),
        migrations.AddConstraint(
            model_name='tenantinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('tenant', 'email'), name='uniq_pending_invite_per_tenant_email'),
        ),
        migrations.AddIndex(
            model_name='tenantdomain',
            index=models.Index(fields=['tenant', 'domain'], name='tenant_doma_tenant__96c5cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantdomain',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('tenant',), name='uniq_primary_domain_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='tenantbilling',
            index=models.Index(fields=['tenant', 'billing_period_start'], name='tenant_bill_tenant__7380f5_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantbilling',
            index=models.Index(fields=['invoice_number'], name='tenant_bill_invoice_d3af13_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantbilling',
            index=models.Index(fields=['status'], name='tenant_bill_status_ccb8ca_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantbilling',
            index=models.Index(fields=['due_date'], name='tenant_bill_due_dat_99a119_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantbilling',
            constraint=models.CheckConstraint(check=models.Q(('total_amount__gte', 0)), name='billing_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tenantbilling',
            constraint=models.CheckConstraint(check=models.Q(('billing_period_end__gte', models.F('billing_period_start'))), name='billing_period_order'),
        ),
        migrations.AddIndex(
            model_name='tenantactivitylog',
            index=models.Index(fields=['tenant', 'created_at'], name='tenant_acti_tenant__8fa769_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantactivitylog',
            index=models.Index(fields=['action'], name='tenant_acti_action_50dd16_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantactivitylog',
            index=models.Index(fields=['user'], name='tenant_acti_user_id_a9a578_idx'),
        ),
        migrations.AddIndex(
            model_name='seatassignment',
            index=models.Index(fields=['tenant', 'module'], name='seat_assign_tenant__4b68ec_idx'),
        ),
        migrations.AddIndex(
            model_name='seatassignment',
            index=models.Index(fields=['user_sub'], name='seat_assign_user_su_02aec2_idx'),
        ),
        migrations.AddIndex(
            model_name='seatassignment',
            index=models.Index(fields=['active'], name='seat_assign_active_4f4d16_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seatassignment',
            unique_together={('tenant', 'module', 'user_sub')},
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['tenant', 'module'], name='licenses_tenant__f7f545_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['active'], name='licenses_active_b00a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['valid_until'], name='licenses_valid_u_29a980_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='license',
            unique_together={('tenant', 'module')},
        ),
    ]
