# Generated by Django 4.2.25 on 2025-11-07 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='tenants.tenant'),
        ),
    ]
