# Generated by Django 4.2.25 on 2025-11-07 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('hr', '0004_rename_hr_departme_tenant__a5f4ee_idx_hr_departme_tenant__9b5c3d_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='department',
            new_name='hr_departme_tenant__a5f4ee_idx',
            old_name='hr_departme_tenant__9b5c3d_idx',
        ),
        migrations.RemoveField(
            model_name='department',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='department',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='tenant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='tenants.tenant'),
        ),
    ]
